apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: localhost:5000/everyhook/badger-consumer
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ZK_URL
              value: zk-persistent:2181
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
spec:
  selector:
    app: consumer
  ports:
    - port: 8080
      targetPort: 8088
  type: LoadBalancer