apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider
  template:
    metadata:
      labels:
        app: provider
    spec:
      containers:
        - name: provider
          image: docker.io/everyhook/badger-provider
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ZK_URL
              value: zk-persistent:2181
---
apiVersion: v1
kind: Service
metadata:
  name: provider
spec:
  selector:
    app: provider
  ports:
    - port: 701
      targetPort: 8080
  type: LoadBalancer