rpc:
  serviceName: badger-consumer
  port: 11311
zk:
  address: ${ZK_URL:127.0.0.1:2181}

tcc.enabled: true
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/consumer
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  sql:
    init:
      mode: always