spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local

rpc:
  serviceName: badger-example
  port: 123
server.port: 3333
zk:
  address: 127.0.0.1:2181

---
spring:
  config:
    activate:
      on-profile: test
server.port: 3335
rpc:
  serviceName: badger-example
  port: 456

zk:
  address: 127.0.0.1:2181