spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local

rpc:
  serviceName: badger-example
  port: 11311

zk:
  address: 127.0.0.1:2181

---
spring:
  config:
    activate:
      on-profile: test

rpc:
  serviceName: badger-example
  port: 11311

zk:
  address: 127.0.0.1:2181